name: Deploy to GitHub Pages

on:
  # Se ejecuta en los pushes al branch `main`
  push:
    branches: [master]
  # Te permite ejecutar este workflow manualmente desde la pestaña Actions
  workflow_dispatch:

# Permisos para el GITHUB_TOKEN para permitir el despliegue
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Install, build, and upload your site
        uses: withastro/action@v3
        # with:
        # path: . # La ruta raíz de tu proyecto de Astro. (opcional)
        # node-version: 20 # La versión de Node.js a usar. (opcional)
        # package-manager: npm # El gestor de paquetes a usar. (opcional)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
